[env:promicro]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino

; ArduinoJoystickLibrary for USB HID gamepad
lib_deps = mheironimus/Joystick@^2.1.1

; Firmware version
joystick_version = 2.7

; Override the USB product name to mine
board_build.usb_product = "Monkey_Ball_Joystick_v${this.joystick_version}"

; Override the VID for the device so that we can have it display my username instead
; Looks weird but this is what I found for how to do it
build_unflags =
    -DUSB_VID=0x1B4F
    "-DUSB_MANUFACTURER=\"SparkFun\""
build_flags =
    -DUSB_VID=0x1209
    -DUSB_MANUFACTURER='"ShellHg"'
    -DFIRMWARE_VERSION='"${this.joystick_version}"'

; Rename firmware.hex with version number after build
extra_scripts = post:rename_firmware.py

; Monitor serial output
monitor_speed = 115200
