[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

; Upload as "Serial + Keyboard + Mouse + Joystick"
; In Arduino IDE, set devie as Tools -> USB Type -> "Keyboard + Mouse + Joystick"
; This defines JOYSTICK_INTERFACE which the firmware requires
build_flags =
    -D USB_SERIAL_HID
    -D LAYOUT_US_ENGLISH

; Monitor serial output (calibration prompts and debug info)
monitor_speed = 115200
